import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(__dirname, "../../..");
const sourcePath = path.join(repoRoot, "packages/contracts/src/product-copy.json");
const targetPath = path.join(repoRoot, "tools/desktop-helper/src/generated-product-copy.js");

const source = JSON.parse(await readFile(sourcePath, "utf8"));
const output = `// Generated by tools/desktop-helper/scripts/sync_product_copy.mjs. Do not edit by hand.\nexport const productCopy = ${JSON.stringify(source, null, 2)};\n`;

await writeFile(targetPath, output, "utf8");
process.stdout.write(`Synced product copy to ${path.relative(repoRoot, targetPath)}\n`);
